language: java
jdk:
  - openjdk10

services:
 - postgresql

addons:
  postgresql: "9.6"

env:
  global:
    - CONF_FILENAME: travis-config.yml

before_install:
 - psql -c 'create database travis_ci_test;' -U postgres
 - sudo cat /etc/postgresql/9.6/main/postgresql.conf

install: true # Disable default install step. Maven runs install as part of the test life cycle anyway.

script: mvn test -B
