language: java
jdk:
  - oraclejdk9

services:
 - postgresql

addons:
  postgresql: "9.6"

env:
  global:
    - JDBC_DATABASE_URL=jdbc:postgresql://localhost/travis_ci_test
    - JDBC_DATABASE_USERNAME=postgres

before_install:
 - psql -c 'create database travis_ci_test;' -U postgres

install: true # Disable default install step. Maven runs install as part of the test life cycle anyway.

script: mvn test -B
