export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const GET_SHOPPING_LISTS = 'GET_SHOPPING_LISTS';
export const GET_SHOPPING_LISTS_SUCCESS = 'GET_SHOPPING_LISTS_SUCCESS';
export const GET_SHOPPING_LISTS_FAIL = 'GET_SHOPPING_LISTS_FAIL';

export const GET_SHOPPING_LIST = 'GET_SHOPPING_LIST';
export const GET_SHOPPING_LIST_SUCCESS = 'GET_SHOPPING_LIST_SUCCESS';
export const GET_SHOPPING_LIST_FAIL = 'GET_SHOPPING_LIST_FAIL';