export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const GET_ITEM_TYPES = 'GET_ITEM_TYPES';
export const GET_ITEM_TYPES_SUCCESS = 'GET_ITEM_TYPES_SUCCESS';
export const GET_ITEM_TYPES_FAIL = 'GET_ITEM_TYPES_FAIL';

export const GET_SHOPPING_LISTS = 'GET_SHOPPING_LISTS';
export const GET_SHOPPING_LISTS_SUCCESS = 'GET_SHOPPING_LISTS_SUCCESS';
export const GET_SHOPPING_LISTS_FAIL = 'GET_SHOPPING_LISTS_FAIL';

export const GET_SHOPPING_LIST = 'GET_SHOPPING_LIST';
export const GET_SHOPPING_LIST_SUCCESS = 'GET_SHOPPING_LIST_SUCCESS';
export const GET_SHOPPING_LIST_FAIL = 'GET_SHOPPING_LIST_FAIL';

export const ADD_SHOPPING_LIST = 'ADD_SHOPPING_LIST';
export const ADD_SHOPPING_LIST_SUCCESS = 'ADD_SHOPPING_LIST_SUCCESS';
export const ADD_SHOPPING_LIST_FAIL = 'ADD_SHOPPING_LIST_FAIL';

export const UPDATE_SHOPPING_LIST = 'UPDATE_SHOPPING_LIST';
export const UPDATE_SHOPPING_LIST_SUCCESS = 'UPDATE_SHOPPING_LIST_SUCCESS';
export const UPDATE_SHOPPING_LIST_FAIL = 'UPDATE_SHOPPING_LIST_FAIL';

export const DELETE_SHOPPING_LIST = 'DELETE_SHOPPING_LIST';
export const DELETE_SHOPPING_LIST_SUCCESS = 'DELETE_SHOPPING_LIST_SUCCESS';
export const DELETE_SHOPPING_LIST_FAIL = 'DELETE_SHOPPING_LIST_FAIL';

export const ADD_SHOPPING_LIST_ITEM = 'ADD_SHOPPING_LIST_ITEM';
export const ADD_SHOPPING_LIST_ITEM_SUCCESS = 'ADD_SHOPPING_LIST_ITEM_SUCCESS';
export const ADD_SHOPPING_LIST_ITEM_FAIL = 'ADD_SHOPPING_LIST_ITEM_FAIL';

export const UPDATE_SHOPPING_LIST_ITEM = 'UPDATE_SHOPPING_LIST_ITEM';
export const UPDATE_SHOPPING_LIST_ITEM_SUCCESS = 'UPDATE_SHOPPING_LIST_ITEM_SUCCESS';
export const UPDATE_SHOPPING_LIST_ITEM_FAIL = 'UPDATE_SHOPPING_LIST_ITEM_FAIL';

export const DELETE_SHOPPING_LIST_ITEM = 'DELETE_SHOPPING_LIST_ITEM';
export const DELETE_SHOPPING_LIST_ITEM_SUCCESS = 'DELETE_SHOPPING_LIST_ITEM_SUCCESS';
export const DELETE_SHOPPING_LIST_ITEM_FAIL = 'DELETE_SHOPPING_LIST_ITEM_FAIL';

export const EMPTY_CART = 'EMPTY_CART';
export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS';
export const EMPTY_CART_FAIL = 'EMPTY_CART_FAIL';