CREATE TYPE USER_ROLE AS ENUM ('USER', 'ADMIN');

CREATE TABLE application_user (
  id SERIAL PRIMARY KEY,
  username CHARACTER VARYING NOT NULL,
  email CHARACTER VARYING NOT NULL,
  hashed_password CHARACTER VARYING NOT NULL,
  salt CHARACTER VARYING NOT NULL,
  verified BOOLEAN NOT NULL,
  role user_role NOT NULL
)